version: BuildNr.{build}

image: Visual Studio 2015

shallow_clone: true

clone_folder: c:\projects\vfs.smb2

environment:
  app_id: vfs.smb2

  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIGURATION: Release
      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.14393.0"
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIGURATION: Release
      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.14393.0"

build_script:
  - cd ..
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd %app_id%
  - mkdir build
  - cd build
  - cmake -T host=x64 -G "%GENERATOR%" %WINSTORE% -DADDONS_TO_BUILD=%app_id% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_BUILD_TYPE=%CONFIG% -DADDON_SRC_PREFIX=../.. -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
  - cmake --build . --config %CONFIGURATION% --target %app_id%
